export const PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    priceMonthly: 7900,
    priceAnnual: 7900 * 10,
    currency: 'brl',
    highlight: false,
    description: 'Para quem está começando',
    subdesc: '1 profissional',
    features: [
      'Agenda completa',
      'Agendamento online',
      'Clientes ilimitados',
      'Financeiro básico',
      'Suporte por e-mail',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    priceMonthly: 14900,
    priceAnnual: 14900 * 10,
    currency: 'brl',
    highlight: true,
    description: 'O favorito das barbearias',
    subdesc: 'até 5 profissionais',
    features: [
      'Agenda completa',
      'Agendamento online',
      'Clientes ilimitados',
      'Financeiro completo',
      'WhatsApp automático',
      'Comissões automáticas',
      'Relatórios básicos',
      'Suporte via chat',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    priceMonthly: 24900,
    priceAnnual: 24900 * 10,
    currency: 'brl',
    highlight: false,
    description: 'Para quem quer o máximo',
    subdesc: 'Profissionais ilimitados',
    features: [
      'Tudo do Pro',
      'Profissionais ilimitados',
      'Controle de estoque',
      'CRM avançado',
      'Relatórios avançados',
      'Multi-unidade',
      'API de integração',
      'Suporte prioritário 24h',
    ],
  },
]
